meta_product_name: "Asyla"
meta_title: "Asyla - Saving-time, Saving Lives"
meta_description: "Asyla, a tech app, that is changing the face of refugee resettlement in North America."
meta_image: "logo_vector-01.png" # should exist in `app/assets/images/`
twitter_account: "@lewagon"   # required for Twitter Cards

